import { redirect } from "next/navigation";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { Prisma } from "@prisma/client";
import Link from "next/link";
import DashboardNav from "@/components/dashboard-nav";
// ClientPanels will be defined inline for now

const savedPhotographerSelect = Prisma.validator<Prisma.PhotographerProfileSelect>()({
  id: true,
  userId: true,
  headline: true,
  city: true,
  verificationStatus: true,
  hourlyRate: true,
  fullDayRate: true,
  travelRadiusKm: true,
  tags: true,
  services: true,
  user: {
    select: {
      name: true,
      email: true,
      phone: true,
    },
  },
  reviews: {
    take: 1,
    orderBy: { createdAt: "desc" },
    select: { rating: true },
  },
});

type SavedPhotographerSummary = Prisma.PhotographerProfileGetPayload<{ select: typeof savedPhotographerSelect }>;

type PhotographerFollowDelegate = {
  findMany: (args: { where: { clientId: string }; select: { photographerId: true }; take: number }) => Promise<{ photographerId: string }[]>;
};

function photographerFollowDelegate(): PhotographerFollowDelegate {
  const delegate = (prisma as unknown as { photographerFollow?: PhotographerFollowDelegate }).photographerFollow;
  if (!delegate) {
    throw new Error(
      "PhotographerFollow delegate is unavailable. Ensure Prisma client is generated by running `npx prisma generate`."
    );
  }
  return delegate;
}

async function getClientDashboardData(userId: string) {
  const profile = await prisma.clientProfile.findUnique({
    where: { userId },
    include: {
      user: true,
    },
  });

  const activeRequests = await prisma.booking.count({
    where: { clientId: userId, status: { in: ["REQUESTED", "CONFIRMED"] } },
  });

  const followRecords = await photographerFollowDelegate().findMany({
    where: { clientId: userId },
    select: { photographerId: true },
    take: 24,
  });

  const photographerIds = followRecords.map((f) => f.photographerId);

  const savedPhotographers: SavedPhotographerSummary[] =
    photographerIds.length > 0
      ? await prisma.photographerProfile.findMany({
          where: {
            id: { in: photographerIds },
          },
          orderBy: { createdAt: "desc" },
          select: savedPhotographerSelect,
        })
      : [];

  const bookingRequests = await (prisma as unknown as { bookingRequest?: { findMany: (args: any) => Promise<any[]> } }).bookingRequest?.findMany({
    where: { clientId: userId, status: "SUBMITTED" },
    orderBy: { createdAt: "desc" },
    take: 5,
  }) ?? [];

  return {
    profile,
    activeRequests,
    savedPhotographers,
    bookingRequests,
  };
}

export default async function ClientDashboardPage() {
  const session = await getServerSession(authOptions);

  if (!session?.user?.id || session.user.role !== "CLIENT") {
    redirect("/login?callbackUrl=/client/dashboard");
  }

  const dashboardData = await getClientDashboardData(session.user.id);
  const isEmailVerified = session.user.emailVerified ?? false;

  const savedPhotographers = dashboardData.savedPhotographers ?? [];
  const savedPhotographersCount = savedPhotographers.length;
  const activeRequestsCount = dashboardData.activeRequests ?? 0;
  const bookingRequestsList = dashboardData.bookingRequests ?? [];
  const clientProfile = dashboardData.profile;

  const alerts: Array<{ title: string; description: string; action: { label: string; href: string } }> = [];

  if (!isEmailVerified) {
    alerts.push({
      title: "Verify your email",
      description: "Complete the OTP step to unlock trusted bookings and protect your account.",
      action: { label: "Verify now", href: "/settings/verification" },
    });
  }

  if (bookingRequestsList.length === 0) {
    alerts.push({
      title: "Create your first brief",
      description: "Share shoot details to receive curated photographer recommendations.",
      action: { label: "Create brief", href: "/bookings/new" },
    });
  }
  if (savedPhotographersCount === 0) {
    alerts.push({
      title: "Shortlist photographers",
      description: "Save favourite creators so you can compare quickly with your team.",
      action: { label: "Browse discover", href: "/discover" },
    });
  }

  const quickActions = [
    {
      label: "Create a new brief",
      description: "It takes under two minutes to get personalised matches.",
      href: "/bookings/new",
    },
    {
      label: "Discover photographers",
      description: "Filter by style, verification, and proximity.",
      href: "/discover",
    },
    {
      label: "Complete verification",
      description: "Build trust with the Momentrix badge before outreach.",
      href: "/settings/verification",
    },
  ];

  const progressItems = [
    {
      label: "Verify email",
      done: isEmailVerified,
      href: "/settings/verification",
    },
    {
      label: "Submit a brief",
      done: bookingRequestsList.length > 0,
      href: "/bookings/new",
    },
    {
      label: "Shortlist photographers",
      done: savedPhotographersCount > 0,
      href: "/discover",
    },
    {
      label: "Confirm booking",
      done: activeRequestsCount > 0,
      href: "/bookings",
    },
  ];

  const metricItems = [
    { value: activeRequestsCount, label: "Active bookings" },
    { value: bookingRequestsList.length, label: "Submitted briefs" },
    { value: savedPhotographersCount, label: "Shortlisted creators" },
  ];

  return (
    <>
      <DashboardNav />
      <div className="mx-auto min-h-screen w-full max-w-6xl px-6 py-10 text-slate-100">
        <header className="mb-12 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
          <div>
            <p className="chip">Client cockpit</p>
            <h1 className="mt-3 text-3xl font-semibold text-white">Discover, brief, book.</h1>
            <p className="text-sm text-slate-300">
              Welcome back, {session.user.name ?? "there"}. Pick up right where you left off.
            </p>
          </div>
          <div className="flex gap-3">
            <Link
              href="/discover"
              className="rounded-full border border-white/15 px-5 py-2 text-sm font-medium text-white transition hover:border-brand-300/60 hover:text-brand-100"
            >
              Find photographers
            </Link>
            <Link
              href="/bookings/new"
              className="rounded-full bg-gradient-to-r from-brand-400 to-brand-600 px-5 py-2 text-sm font-semibold text-white shadow-soft-glow transition hover:from-brand-300 hover:to-brand-500"
            >
              Create booking brief
            </Link>
          </div>
        </header>

        {alerts.length > 0 ? (
          <div className="mb-8 space-y-3">
            {alerts.map((alert, idx) => (
              <div
                key={idx}
                className="rounded-4xl border border-brand-400/30 bg-brand-500/10 p-5 text-sm"
              >
                <div className="flex items-start justify-between gap-4">
                  <div className="flex-1">
                    <h3 className="font-semibold text-white">{alert.title}</h3>
                    <p className="mt-1 text-slate-300">{alert.description}</p>
                  </div>
                  <Link
                    href={alert.action.href}
                    className="shrink-0 rounded-full bg-brand-500 px-4 py-2 text-xs font-semibold text-white transition hover:bg-brand-400"
                  >
                    {alert.action.label} →
                  </Link>
                </div>
              </div>
            ))}
          </div>
        ) : null}

        <div className="mb-8 grid gap-4 sm:grid-cols-3">
          {quickActions.map((action, idx) => (
            <Link
              key={idx}
              href={action.href}
              className="rounded-4xl border border-white/10 bg-white/5 p-6 transition hover:border-brand-300/60"
            >
              <h3 className="font-semibold text-white">{action.label}</h3>
              <p className="mt-2 text-xs text-slate-400">{action.description}</p>
            </Link>
          ))}
        </div>

        <div className="mb-8 rounded-4xl border border-white/10 bg-white/5 p-6">
          <h2 className="text-lg font-semibold text-white">Your progress</h2>
          <div className="mt-4 space-y-3">
            {progressItems.map((item, idx) => (
              <div key={idx} className="flex items-center justify-between">
                <div className="flex items-center gap-3">
                  <div
                    className={`h-6 w-6 rounded-full border-2 flex items-center justify-center ${
                      item.done
                        ? "border-brand-400 bg-brand-500/20"
                        : "border-slate-600 bg-transparent"
                    }`}
                  >
                    {item.done ? (
                      <svg className="h-4 w-4 text-brand-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                      </svg>
                    ) : null}
                  </div>
                  <span className={`text-sm ${item.done ? "text-slate-300" : "text-slate-500"}`}>
                    {item.label}
                  </span>
                </div>
                {item.href ? (
                  <Link
                    href={item.href}
                    className="text-xs text-brand-300 hover:text-brand-200"
                  >
                    {item.done ? "View" : "Start"}
                  </Link>
                ) : null}
              </div>
            ))}
          </div>
        </div>

        <main className="grid gap-8 xl:grid-cols-[2fr_1fr]">
          <section className="space-y-6">
            <div className="rounded-4xl border border-white/10 bg-white/5 p-6">
              <h2 className="text-lg font-semibold text-white">Your requests</h2>
              <div className="mt-4 grid gap-4 sm:grid-cols-3">
                {metricItems.map((item) => (
                  <div key={item.label} className="text-center">
                    <p className="text-3xl font-semibold text-white">{item.value}</p>
                    <p className="mt-1 text-xs text-slate-400">{item.label}</p>
                  </div>
                ))}
              </div>
            </div>

            {/* Client panels will be added here - for now showing a placeholder */}
            <div className="rounded-4xl border border-white/10 bg-white/5 p-6">
              <h3 className="text-lg font-semibold text-white">Shortlisted photographers</h3>
              <div className="mt-4 grid gap-4 sm:grid-cols-2">
                {savedPhotographers.length > 0 ? (
                  savedPhotographers.slice(0, 4).map((photographer) => {
                    const tags = Array.isArray(photographer.tags)
                      ? (photographer.tags as string[]).slice(0, 3)
                      : [];
                    const displayName =
                      photographer.user?.name ?? photographer.headline ?? "Momentrix photographer";
                    return (
                      <article key={photographer.id} className="rounded-3xl border border-white/10 bg-white/5 p-4">
                        <div className="space-y-2">
                          <p className="text-sm font-semibold text-white">{displayName}</p>
                          <p className="text-xs text-slate-400">
                            {photographer.city ?? "Location TBD"} • travels {photographer.travelRadiusKm} km
                          </p>
                          <Link
                            href={`/photographers/${photographer.id}`}
                            className="inline-flex items-center gap-1 text-xs font-semibold text-brand-200 hover:text-brand-100"
                          >
                            View profile →
                          </Link>
                        </div>
                      </article>
                    );
                  })
                ) : (
                  <div className="col-span-2 rounded-3xl border border-dashed border-white/20 bg-white/5 p-6 text-sm text-slate-300">
                    <p>Shortlist photographers from discovery to curate your favourites.</p>
                    <Link href="/discover" className="mt-2 inline-flex text-brand-200">
                      Browse discover →
                    </Link>
                  </div>
                )}
              </div>
            </div>
          </section>
        </main>
      </div>
    </>
  );
}

