import { redirect } from "next/navigation";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import Link from "next/link";
import DashboardNav from "@/components/dashboard-nav";
import { format } from "date-fns";

type BookingRequestDelegate = {
  findMany: (...args: any[]) => Promise<any[]>;
};

function bookingRequestDelegate(): BookingRequestDelegate {
  const delegate = (prisma as unknown as { bookingRequest?: BookingRequestDelegate }).bookingRequest;
  if (!delegate) {
    throw new Error(
      "BookingRequest delegate is unavailable. Ensure Prisma client is generated by running `npx prisma generate`."
    );
  }
  return delegate;
}

type SocialAccountDelegate = {
  findMany: (...args: any[]) => Promise<any[]>;
};

function socialAccountDelegate(): SocialAccountDelegate {
  const delegate = (prisma as unknown as { socialAccount?: SocialAccountDelegate }).socialAccount;
  if (!delegate) {
    throw new Error(
      "SocialAccount delegate is unavailable. Ensure Prisma client is generated by running `npx prisma generate`."
    );
  }
  return delegate;
}

async function getPhotographerDashboardData(userId: string) {
  const profile = await prisma.photographerProfile.findUnique({
    where: { userId },
    include: {
      portfolioItems: {
        take: 3,
        orderBy: { createdAt: "desc" },
      },
      posts: {
        take: 3,
        orderBy: { createdAt: "desc" },
      },
      reviews: {
        take: 3,
        orderBy: { createdAt: "desc" },
        include: {
          booking: true,
        },
      },
      availability: {
        take: 3,
        orderBy: { startTime: "asc" },
      },
    },
  });

  const pendingBookings = await prisma.booking.count({
    where: { photographerId: userId, status: "REQUESTED" },
  });

  const bookingRequests = await bookingRequestDelegate().findMany({
    where: { status: "SUBMITTED" },
    orderBy: { createdAt: "desc" },
    take: 5,
  });

  const socialAccounts = await socialAccountDelegate().findMany({
    where: { userId },
    select: {
      provider: true,
      followerCount: true,
      verifiedAt: true,
    },
  });

  return {
    profile,
    pendingBookings,
    bookingRequests,
    socialAccounts,
  };
}

export default async function PhotographerDashboardPage() {
  const session = await getServerSession(authOptions);

  if (!session?.user?.id || session.user.role !== "PHOTOGRAPHER") {
    redirect("/login?callbackUrl=/photographer/dashboard");
  }

  const dashboardData = await getPhotographerDashboardData(session.user.id);
  const isEmailVerified = session.user.emailVerified ?? false;

  const profile = dashboardData.profile;
  const pendingBookingsCount = dashboardData.pendingBookings ?? 0;
  const bookingRequestsList = dashboardData.bookingRequests ?? [];
  const socialAccounts = dashboardData.socialAccounts ?? [];

  const hasPortfolio = (profile?.portfolioItems?.length ?? 0) > 0;
  const hasAvailability = Array.isArray(profile?.availability) ? (profile.availability.length ?? 0) > 0 : false;
  const hasSocialBadge = socialAccounts.some((account) => Boolean(account.verifiedAt));

  const alerts: Array<{ title: string; description: string; action: { label: string; href: string } }> = [];

  if (!isEmailVerified) {
    alerts.push({
      title: "Verify your email",
      description: "Complete the OTP step to unlock trusted bookings and protect your account.",
      action: { label: "Verify now", href: "/settings/verification" },
    });
  }

  if (!hasPortfolio) {
    alerts.push({
      title: "Upload portfolio highlights",
      description: "Showcase your signature shoots to convert more briefs.",
      action: { label: "Add work", href: "/studio/portfolio" },
    });
  }
  if (!hasAvailability) {
    alerts.push({
      title: "Publish availability",
      description: "Share open slots so clients can book instantly.",
      action: { label: "Update availability", href: "/studio/availability" },
    });
  }
  if (!hasSocialBadge) {
    alerts.push({
      title: "Link social profiles",
      description: "Connect Instagram, Facebook, or X to earn the Momentrix verified badge.",
      action: { label: "Connect socials", href: "/settings/verification" },
    });
  }

  const quickActions = [
    {
      label: "Update availability",
      description: "Keep your travel radius and slots fresh for instant bookings.",
      href: "/studio/availability",
    },
    {
      label: "Upload new work",
      description: "Add your latest shoots to inspire upcoming briefs.",
      href: "/studio/portfolio",
    },
    {
      label: "Share a reel",
      description: "Stay top-of-mind by posting behind-the-scenes stories.",
      href: "/studio/posts",
    },
  ];

  const progressItems = [
    {
      label: "Complete profile",
      done: Boolean(profile?.headline && profile?.bio),
      href: "/onboarding/photographer",
    },
    {
      label: "Upload portfolio",
      done: hasPortfolio,
      href: "/studio/portfolio",
    },
    {
      label: "Publish availability",
      done: hasAvailability,
      href: "/studio/availability",
    },
    {
      label: "Link socials",
      done: hasSocialBadge && isEmailVerified,
      href: "/settings/verification",
    },
  ];

  const metricItems = [
    { value: pendingBookingsCount, label: "Pending bookings" },
    { value: bookingRequestsList.length, label: "New briefs nearby" },
    {
      value: profile?.posts?.length ?? 0,
      label: "Recent social posts",
    },
  ];

  return (
    <>
      <DashboardNav />
      <div className="mx-auto min-h-screen w-full max-w-6xl px-6 py-10 text-slate-100">
        <header className="mb-12 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
          <div>
            <p className="chip">Creator workspace</p>
            <h1 className="mt-3 text-3xl font-semibold text-white">Showcase, respond, deliver.</h1>
            <p className="text-sm text-slate-300">
              Welcome back, {session.user.name ?? "there"}. Pick up right where you left off.
            </p>
          </div>
          <div className="flex gap-3">
            <Link
              href="/studio/portfolio"
              className="rounded-full border border-white/15 px-5 py-2 text-sm font-medium text-white transition hover:border-brand-300/60 hover:text-brand-100"
            >
              Manage portfolio
            </Link>
            <Link
              href="/studio/availability"
              className="rounded-full bg-gradient-to-r from-brand-400 to-brand-600 px-5 py-2 text-sm font-semibold text-white shadow-soft-glow transition hover:from-brand-300 hover:to-brand-500"
            >
              Update availability
            </Link>
          </div>
        </header>

        {alerts.length > 0 ? (
          <div className="mb-8 space-y-3">
            {alerts.map((alert, idx) => (
              <div
                key={idx}
                className="rounded-4xl border border-brand-400/30 bg-brand-500/10 p-5 text-sm"
              >
                <div className="flex items-start justify-between gap-4">
                  <div className="flex-1">
                    <h3 className="font-semibold text-white">{alert.title}</h3>
                    <p className="mt-1 text-slate-300">{alert.description}</p>
                  </div>
                  <Link
                    href={alert.action.href}
                    className="shrink-0 rounded-full bg-brand-500 px-4 py-2 text-xs font-semibold text-white transition hover:bg-brand-400"
                  >
                    {alert.action.label} →
                  </Link>
                </div>
              </div>
            ))}
          </div>
        ) : null}

        <div className="mb-8 grid gap-4 sm:grid-cols-3">
          {quickActions.map((action, idx) => (
            <Link
              key={idx}
              href={action.href}
              className="rounded-4xl border border-white/10 bg-white/5 p-6 transition hover:border-brand-300/60"
            >
              <h3 className="font-semibold text-white">{action.label}</h3>
              <p className="mt-2 text-xs text-slate-400">{action.description}</p>
            </Link>
          ))}
        </div>

        <div className="mb-8 rounded-4xl border border-white/10 bg-white/5 p-6">
          <h2 className="text-lg font-semibold text-white">Your progress</h2>
          <div className="mt-4 space-y-3">
            {progressItems.map((item, idx) => (
              <div key={idx} className="flex items-center justify-between">
                <div className="flex items-center gap-3">
                  <div
                    className={`h-6 w-6 rounded-full border-2 flex items-center justify-center ${
                      item.done
                        ? "border-brand-400 bg-brand-500/20"
                        : "border-slate-600 bg-transparent"
                    }`}
                  >
                    {item.done ? (
                      <svg className="h-4 w-4 text-brand-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                      </svg>
                    ) : null}
                  </div>
                  <span className={`text-sm ${item.done ? "text-slate-300" : "text-slate-500"}`}>
                    {item.label}
                  </span>
                </div>
                {item.href ? (
                  <Link
                    href={item.href}
                    className="text-xs text-brand-300 hover:text-brand-200"
                  >
                    {item.done ? "View" : "Start"}
                  </Link>
                ) : null}
              </div>
            ))}
          </div>
        </div>

        <main className="grid gap-8 xl:grid-cols-[2fr_1fr]">
          <section className="space-y-6">
            <div className="rounded-4xl border border-white/10 bg-white/5 p-6">
              <h2 className="text-lg font-semibold text-white">At a glance</h2>
              <div className="mt-4 grid gap-4 sm:grid-cols-3">
                {metricItems.map((item) => (
                  <div key={item.label} className="text-center">
                    <p className="text-3xl font-semibold text-white">{item.value}</p>
                    <p className="mt-1 text-xs text-slate-400">{item.label}</p>
                  </div>
                ))}
              </div>
            </div>

            <div className="grid gap-6 lg:grid-cols-2">
              <div className="rounded-4xl border border-white/10 bg-white/5 p-6">
                <h3 className="text-lg font-semibold text-white">Portfolio highlights</h3>
                <div className="mt-4 space-y-3">
                  {profile?.portfolioItems?.length ? (
                    profile.portfolioItems.map((item) => (
                      <article key={item.id} className="rounded-3xl border border-white/10 bg-white/5 p-4">
                        <p className="text-sm font-semibold text-white">{item.title}</p>
                        <p className="text-xs text-slate-400">{item.location ?? "Location TBD"}</p>
                      </article>
                    ))
                  ) : (
                    <div className="rounded-3xl border border-dashed border-white/20 bg-white/5 p-6 text-sm text-slate-300">
                      <p>Upload portfolio pieces to attract new briefs.</p>
                      <Link href="/studio/portfolio/new" className="mt-2 inline-flex text-brand-200">
                        Take action →
                      </Link>
                    </div>
                  )}
                </div>
              </div>
              <div className="rounded-4xl border border-white/10 bg-white/5 p-6">
                <h3 className="text-lg font-semibold text-white">Recent social posts</h3>
                <div className="mt-4 space-y-3">
                  {profile?.posts?.length ? (
                    profile.posts.map((post) => (
                      <article key={post.id} className="rounded-3xl border border-white/10 bg-white/5 p-4">
                        <p className="text-sm font-semibold text-white">{post.title}</p>
                        <p className="text-xs text-slate-400">
                          {post.likes} likes • {post.enquiries} enquiries
                        </p>
                      </article>
                    ))
                  ) : (
                    <div className="rounded-3xl border border-dashed border-white/20 bg-white/5 p-6 text-sm text-slate-300">
                      <p>Share behind-the-scenes clips to stay top of mind.</p>
                      <Link href="/studio/posts/new" className="mt-2 inline-flex text-brand-200">
                        Take action →
                      </Link>
                    </div>
                  )}
                </div>
              </div>
              <div className="rounded-4xl border border-white/10 bg-white/5 p-6 lg:col-span-2">
                <h3 className="text-lg font-semibold text-white">Upcoming availability</h3>
                <div className="mt-4 space-y-3 text-sm text-slate-300">
                  {profile?.availability?.length ? (
                    profile.availability.map((slot: any) => (
                      <div
                        key={slot.id}
                        className="flex flex-col gap-1 rounded-3xl border border-white/10 bg-white/5 px-4 py-3 text-xs text-slate-300 sm:flex-row sm:items-center sm:justify-between"
                      >
                        <div>
                          <p className="font-semibold text-white">
                            {format(new Date(slot.startTime), "MMM d, yyyy p")} —{" "}
                            {format(new Date(slot.endTime), "p")}
                          </p>
                          <p className="text-[11px] uppercase tracking-[0.2em] text-brand-200">
                            {slot.isBooked ? "Reserved" : "Available"}
                          </p>
                        </div>
                        {!slot.isBooked ? (
                          <Link
                            href="/studio/availability"
                            className="inline-flex items-center justify-center rounded-full border border-white/15 px-3 py-1 text-[11px] font-semibold text-white transition hover:border-brand-300/60 hover:text-brand-100"
                          >
                            Edit slot
                          </Link>
                        ) : null}
                      </div>
                    ))
                  ) : (
                    <div className="rounded-3xl border border-dashed border-white/20 bg-white/5 p-6 text-sm text-slate-300">
                      <p>Publish your travel radius and availability slots.</p>
                      <Link href="/studio/availability" className="mt-2 inline-flex text-brand-200">
                        Take action →
                      </Link>
                    </div>
                  )}
                </div>
              </div>
            </div>
          </section>

          <aside className="space-y-6">
            <div className="rounded-4xl border border-brand-400/40 bg-brand-500/10 p-6">
              <h3 className="text-sm font-semibold uppercase tracking-wide text-brand-100">
                Identity verification
              </h3>
              <p className="mt-2 text-sm text-slate-200">
                {isEmailVerified
                  ? "Your email is verified. Link your socials next to earn the verified badge."
                  : "Verify your email and link your socials to unlock premium leads and faster approvals."}
              </p>
              <Link
                href="/settings/verification"
                className="mt-4 inline-flex items-center justify-center rounded-full bg-white px-4 py-2 text-sm font-semibold text-midnight-900"
              >
                {isEmailVerified ? "Manage verification" : "Verify now"}
              </Link>
            </div>

            <div className="rounded-4xl border border-white/10 bg-white/5 p-6 text-sm text-slate-300">
              <h3 className="text-sm font-semibold uppercase tracking-wide text-slate-200">Open briefs near you</h3>
              {bookingRequestsList.length === 0 ? (
                <>
                  <p className="mt-3">No new briefs available. Keep your portfolio updated to attract more clients.</p>
                  <Link
                    href="/studio/portfolio"
                    className="mt-4 inline-flex items-center justify-center rounded-full border border-white/15 px-4 py-2 text-xs font-semibold text-white transition hover:border-brand-300/60 hover:text-brand-100"
                  >
                    Refresh portfolio
                  </Link>
                </>
              ) : (
                <ul className="mt-4 space-y-3">
                  {bookingRequestsList.slice(0, 4).map((item: any) => {
                    const start = item.startTime ? format(new Date(item.startTime), "MMM d, yyyy") : null;
                    const created = item.createdAt ? format(new Date(item.createdAt), "MMM d, yyyy") : null;
                    return (
                      <li
                        key={item.id}
                        className="rounded-3xl border border-white/10 bg-white/3 p-4 text-xs text-slate-300"
                      >
                        <div className="flex items-center justify-between gap-3">
                          <p className="text-sm font-semibold text-white">{item.eventName ?? "Untitled shoot"}</p>
                          <span className="rounded-full border border-white/10 px-3 py-1 text-[11px] uppercase tracking-wide text-slate-400">
                            {(item.status ?? "pending").replace(/_/g, " ")}
                          </span>
                        </div>
                        <p className="mt-2 text-[11px] uppercase tracking-wide text-brand-200">
                          {item.eventType ?? "Event type"} • {start ?? created ?? "TBD"}
                        </p>
                        <p className="mt-1 text-[11px] text-slate-400">
                          {item.location ?? "Client location hidden"}
                        </p>
                      </li>
                    );
                  })}
                </ul>
              )}
              {bookingRequestsList.length > 0 ? (
                <Link
                  href="/bookings"
                  className="mt-5 inline-flex items-center text-xs font-semibold text-brand-200"
                >
                  View all →
                </Link>
              ) : null}
            </div>
          </aside>
        </main>
      </div>
    </>
  );
}


